FinalProject/FinalProject/FinalProject.csproj, FinalProject/FinalProject/Models/Applicant.cs, FinalProject/FinalProject/Models/Application.cs, FinalProject/FinalProject/Models/Job.cs, FinalProject/FinalProject/Models/Posting.cs, FinalProject/FinalProject/Models/Province.cs, FinalProject/FinalProject/Models/Qualification.cs, FinalProject/FinalProject/Models/School.cs, FinalProject/FinalProject/Models/SchoolFamily.cs, FinalProject/FinalProject/Models/SchoolLevel.cs, FinalProject/FinalProject/Models/SchoolLocation.cs
=> Database first prototype

FinalProject/FinalProject/Views/Home/Index.cshtml, FinalProject/FinalProject/Views/Shared/_Layout.cshtml
Footer and search button added to homepage
=> Footer and Sarch button

FinalProject/FinalProject/Controllers/HomeController.cs, FinalProject/FinalProject/Views/Home/Index.cshtml, FinalProject/FinalProject/Views/Shared/_Layout.cshtml
=> Hide posting results section

FinalProject/FinalProject/Content/bootstrap.css, FinalProject/FinalProject/FinalProject.csproj, FinalProject/FinalProject/Models/Review.cs, FinalProject/FinalProject/Views/Account/Login.cshtml, FinalProject/FinalProject/Views/Account/Register.cshtml, FinalProject/FinalProject/Views/Applicant/Index.cshtml, FinalProject/FinalProject/Views/Application/Index.cshtml, FinalProject/FinalProject/Views/Application/IndexOld.cshtml, FinalProject/FinalProject/Views/Home/Index.cshtml, FinalProject/FinalProject/Views/Portfolio/index.cshtml, FinalProject/FinalProject/Views/Posting/Create.cshtml, FinalProject/FinalProject/Views/Posting/Details.cshtml, FinalProject/FinalProject/Views/Posting/Index.cshtml, FinalProject/FinalProject/Views/Shared/_Layout.cshtml
=> Revert "Changes to Posting page and added container fro all pages"

FinalProject/FinalProject/Views/Application/Delete.cshtml, FinalProject/FinalProject/Views/Application/Details.cshtml, FinalProject/FinalProject/Views/Posting/Create.cshtml, FinalProject/FinalProject/Views/Posting/Delete.cshtml, FinalProject/FinalProject/Views/Posting/Details.cshtml, FinalProject/FinalProject/Views/Posting/Edit.cshtml
Changes to Posting and Applications pages
=> Changes to Posting and Applications pages

FinalProject/FinalProject/Views/Applicant/Index.cshtml, FinalProject/FinalProject/Views/Application/Index.cshtml, FinalProject/FinalProject/Views/Application/IndexOld.cshtml
=> Applications tab done

FinalProject/FinalProject/Views/Home/Index.cshtml
home page search and more searches
=> sample search adn advance search

FinalProject/FinalProject/DAL/Migrations/Configuration.cs
=> Jet sseeding

FinalProject/FinalProject/Controllers/PostingController.cs, FinalProject/FinalProject/Views/Posting/Details.cshtml, FinalProject/FinalProject/Views/Posting/Index.cshtml
=> Postingjet

FinalProject/FinalProject/Controllers/PostingController.cs, FinalProject/FinalProject/Views/Posting/Delete.cshtml, FinalProject/FinalProject/Views/Posting/Edit.cshtml
Edit ,delete, details and index is done for now. need more tweeking add more validiation and concurrency
=> Edit,Delete

FinalProject/FinalProject/DAL/MigratingCopyPasta.txt, FinalProject/FinalProject/DAL/Migrations/SeedData.txt, FinalProject/FinalProject/Models/DataModel/Applicant.cs, FinalProject/FinalProject/Models/DataModel/Job.cs, FinalProject/FinalProject/Models/DataModel/Posting.cs, FinalProject/FinalProject/Models/DataModel/Qualification.cs, FinalProject/FinalProject/Models/DataModel/Requirement.cs
=> TESTASDASDSDSD

FinalProject/FinalProject/Controllers/PostingController.cs, FinalProject/FinalProject/Views/Posting/Edit.cshtml
=> edit is done

FinalProject/FinalProject.Tests/Controllers/HomeControllerTest.cs, FinalProject/FinalProject.sln, FinalProject/FinalProject/Controllers/HomeController.cs, FinalProject/FinalProject/Views/Home/Index.cshtml
only the all the posting list wont show up. search is working with real data
=> Homepagerealdatajet

FinalProject/FinalProject/Controllers/HomeController.cs, FinalProject/FinalProject/Controllers/PostingController.cs, FinalProject/FinalProject/Controllers/SchoolsController.cs, FinalProject/FinalProject/DAL/Migrations/Configuration.cs, FinalProject/FinalProject/FinalProject.csproj, FinalProject/FinalProject/Views/Home/Index.cshtml, FinalProject/FinalProject/Views/Jobs/Index.cshtml, FinalProject/FinalProject/Views/Posting/Create.cshtml, FinalProject/FinalProject/Views/Schools/Create.cshtml, FinalProject/FinalProject/Views/Schools/Delete.cshtml, FinalProject/FinalProject/Views/Schools/Details.cshtml, FinalProject/FinalProject/Views/Schools/Edit.cshtml, FinalProject/FinalProject/Views/Schools/Index.cshtml
fix the homePage everything is working. have a result on dropdownlist
=> Jetgodmode

FinalProject/FinalProject/Views/Jobs/Index.cshtml, FinalProject/FinalProject/Views/Posting/Create.cshtml, FinalProject/FinalProject/Views/Posting/Edit.cshtml
=> Edit changes

FinalProject/FinalProject/Controllers/ApplyController.cs, FinalProject/FinalProject/Views/Applicant/Details.cshtml, FinalProject/FinalProject/Views/Applicant/Index.cshtml, FinalProject/FinalProject/Views/Application/Details.cshtml, FinalProject/FinalProject/Views/Application/Index.cshtml, FinalProject/FinalProject/Views/Apply/Index.cshtml, FinalProject/FinalProject/Views/Archive/IndexApplications.cshtml
fix some databases codes that was missing and index apply is done not the create application yet
=> Applyjobbyjet

FinalProject/FinalProject/Views/Applicant/Details.cshtml, FinalProject/FinalProject/Views/Apply/Index.cshtml, FinalProject/FinalProject/Views/Jobs/Create.cshtml, FinalProject/FinalProject/Views/Jobs/Details.cshtml, FinalProject/FinalProject/Views/Jobs/Index.cshtml, FinalProject/FinalProject/Views/Posting/Create.cshtml
=> Jobs changes

FinalProject/FinalProject/Views/Jobs/Create.cshtml
Last minute changes to create page before presentation
=> Newbranch5

FinalProject/FinalProject/Views/Application/Delete.cshtml, FinalProject/FinalProject/Views/Application/Details.cshtml, FinalProject/FinalProject/Views/Application/Index.cshtml, FinalProject/FinalProject/Views/Archive/IndexApplications.cshtml
Application Details page and Login Page done
=> Application Details page and Login Page done

FinalProject/FinalProject/Views/Portfolio/index.cshtml, FinalProject/FinalProject/Views/Posting/Details.cshtml
=> asdasdasdas

FinalProject/FinalProject/Views/Home/Index.cshtml, FinalProject/FinalProject/Views/Posting/Details.cshtml
=> fix homePage and view posting

FinalProject/FinalProject/Controllers/ArchiveController.cs, FinalProject/FinalProject/FinalProject.csproj, FinalProject/FinalProject/Views/Archive/ArchivePostingDetails.cshtml, FinalProject/FinalProject/Views/Archive/IndexPostings.cshtml
=> fix archivePosting

FinalProject/FinalProject/Controllers/ApplicationController.cs, FinalProject/FinalProject/Controllers/PortfolioController.cs, FinalProject/FinalProject/Views/Application/Details.cshtml, FinalProject/FinalProject/Views/Portfolio/index.cshtml
=> ApplicationStatus is done

FinalProject/FinalProject/Views/Application/Delete.cshtml, FinalProject/FinalProject/Views/Application/Details.cshtml, FinalProject/FinalProject/Views/Apply/AppliedView.cshtml, FinalProject/FinalProject/Views/Home/Index.cshtml, FinalProject/FinalProject/Views/Jobs/Delete.cshtml, FinalProject/FinalProject/Views/Jobs/Details.cshtml, FinalProject/FinalProject/Views/Jobs/Edit.cshtml, FinalProject/FinalProject/Views/Jobs/Index.cshtml, FinalProject/FinalProject/Views/Posting/Archive.cshtml, FinalProject/FinalProject/Views/Posting/CreateStart.cshtml, FinalProject/FinalProject/Views/Posting/Details.cshtml, FinalProject/FinalProject/Views/Posting/Edit.cshtml
Changes to Jobs and Edit Posting.. still working on it
=> Changes to Jobs and Edit Posting.. still working on it
